//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.06 at 05:50:00 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/Schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example.schema;
